### ISSUE TITLE
About prediction model for feature selction

### ISSUE THREAD

**Issue by hello-maker** [addb-swstarlab/CCDT#15]
When I looked at your code, I think you used a random forest model to select the features that are important for predicting database performance because you can use the feature_importance_ function built into the random forest model. 

However, the performance of the randomforest prediction model seems to be rather poor, so I think the reliability of the important features extracted by the prediction model is low. So, have you tried using a model that can utilize attention scores other than the randomforest or adaboost model, or have you tried using another kind of model?

**Comment by Kwon-sein** [comment]
Hi.
Thanks for asking the question about my code.

First, the reason for using random forest is not to use the feature_importances_ function, but to extract importace features through SHAP Value.

 Also, as you can see in the code, I tried using XGBRegressor and AdaBoostRegressor in addition to random forest, and XGBRegressor had the highest R2 score, so I used that model to get SHAP Value.

Also, as the questioner said, the performance of the random forest prediction model seems to be somewhat inferior, so I think it is correct that the reliability of the important features extracted from the prediction model is low, and that is why I can say that I used XGBRegressor.

I hope my answer was helpful.
