### ISSUE TITLE
About reason of score.

### ISSUE THREAD

**Issue by hello-maker** [addb-swstarlab/CCDT#18]
Hi,
First of all, thanks for the great research.

My question is how to calculate the score for each config to pick the best performing one. I noticed that the range (scale) of values for TPS and latency are very different. If I calculate the ratio of those attributes without any normalization or scaling for these two values, it seems that the relatively large scale of TPS will have a dominant effect on the score, is there any particular reason for calculating the score without scaling?

**Comment by Kwon-sein** [comment]
Thank you for the good question.

It is true that the data trends of tps and latency are different.

However, there appears to be no difference in the scores before and after scaling.
I will attach the results obtained when the score was obtained after scaling.

![image](https://github.com/addb-swstarlab/CCDT/assets/72485253/4a19c6f8-b5ef-4f23-ac12-8765d9aeba30)
