### ISSUE TITLE
About tps, latency

### ISSUE THREAD

**Issue by kkIIun** [addb-swstarlab/CCDT#21]
Hello,

I have two question.
what does tps, latency mean in testing_tpcc.ipynb?

and why dose the score imply tps/latency?

Thanks!

**Comment by Kwon-sein** [comment]
HI,
Thank you for your question.

tps is the amount of data processed.
Latency is the delay time (the time it takes for data to be processed).

The reason for using tps/latency as the score is to compare the amount of data processed within the same delay time for all metric samples.

If you have any additional questions, please leave a issue.
