### ISSUE TITLE
About Code

### ISSUE THREAD

**Issue by whduddhks** [addb-swstarlab/CCDT#22]
Hello, I have some questions about the code.

In the "testing_tpcc_ipynb" file

Cell 6 and 7 is the same code?

In cell 6, you append best config in variable "best_config".
But you declare "best_config" as empty list in cell 7 and didn't use the "best_config" in cell 7.
So I wonder why you declare the "bset_config".

And cell 5 and 8, the result of metrics.sort_value('score', ascending=False) is different.
Can you tell me why?

Thank you.

**Comment by Kwon-sein** [comment]
Hi,

Thank you for your question.
First of all, cells 6 and 7 are not the same codes.

cell 6 : For find good performance among the all metrics samples
cell 7 : This code extracts the index of the metric extracted from cell 6 and loads the config file corresponding to the metric (cell 7,8)

Second, I will edit the part where the "best_config" list is not used in cell6 with a comment.

Third, In the case of cells 5 and 8, these are test cells using different data, and we will comment out those cells as well.
