### ISSUE TITLE
Questions about data genration method

### ISSUE THREAD

**Issue by huijunjin** [addb-swstarlab/CCDT#23]
Hello, 

Why do you use LHS for data generation, how about using other methods like Monte Carlo Sampling or Quasi-random Sequences etc.?

Thanks.

**Comment by Kwon-sein** [comment]
Hello, thank you for your interest in my code.

The reason for using LHS Sampling is that it has the advantage of efficiently analyzing the variable space at minimal cost and LHS Sampling is often used in existing database parameter tuning papers.

We will try using the two sampling techniques you mentioned later.

Thanks.

**Comment by huijunjin** [comment]
Thanks for your answer.
