### ISSUE TITLE
About Classifier Hyper parameter.

### ISSUE THREAD

**Issue by Hyunjining** [addb-swstarlab/CCDT#8]
Hello,

What criteria did you set the hyperparameters for the XGBClassifier in CCDT/new_model/main_classification.py?

I wonder how the results obtained when adjusting the hyperparameter values are different.

Thanks for reading.

**Comment by Kwon-sein** [comment]
Hi.
Thanks for your interest in my  'CCDT' code.

First, I performed hyperparameter tuning using the randomsearch method.

Second, when I  using the tuned hyperparameters, the balanced accuracy of the model improved by as little as 3% and as much as 30%. ( 0.62 -> 0.93 , 0.86 -> 0.93 ...)

Additionally, the reason for using balanced accuracy is that the data is imbalanced.

I hope my explanation was helpful.
