### ISSUE TITLE
About Model Selection

### ISSUE THREAD

**Issue by hello-maker** [addb-swstarlab/CCDT#9]
Why did you choose the ensemble model even though there are various model other than ensemble architecture among supervised learning techniques?

**Comment by Kwon-sein** [comment]
Hi,
Thanks for asking a question about my code.

First, our task is to predic the cluster through the thoughput and latency of the configuraiton. That is, it is a classification model, and an ensemble model was seleced as a suitable model. So we experimented with various ensemble models.
And also, we tried using a linear model for this task before, but it showed low accuracy, so we used an ensemble model.

I hope my answer is appropriate to your question.
Thanks.
